# Generated by Django 2.2.10 on 2021-04-22 19:38

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('datafile', models.FileField(upload_to='img/%y')),
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title_of_the_audiobook', models.CharField(max_length=100)),
                ('Author_of_the_title', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconda', models.PositiveIntegerField()),
                ('Upload_time', models.DateTimeField(auto_now_add=True, null=True, validators=[app1.models.validate_date])),
                ('file_type', models.CharField(default='audio', editable=False, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('datafile', models.FileField(upload_to='img/%y')),
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name_of_the_podcast', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconda', models.PositiveIntegerField()),
                ('Upload_time', models.DateTimeField(auto_now_add=True, null=True, validators=[app1.models.validate_date])),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(choices=[('people_1', 'people_1'), ('people_2', 'people_2'), ('people_3', 'people_3'), ('people_4', 'people_4'), ('people_5', 'people_5'), ('people_6', 'people_1'), ('people_7', 'people_7'), ('people_8', 'people_8'), ('people_9', 'people_9'), ('people_10', 'people_10')], default='people_1', max_length=100)),
                ('file_type', models.CharField(default='podcast', editable=False, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('datafile', models.FileField(upload_to='img/%y')),
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name_of_the_song', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconda', models.PositiveIntegerField()),
                ('Upload_time', models.DateTimeField(auto_now_add=True, null=True, validators=[app1.models.validate_date])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
